# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 836049966ebbbed7b0e46f45bc7c248c1f39e5a00ae300baa4f5923ca6825ac94d0ffa1239456d14bd373863194c7d65c9a757bb52f1162b740a0d23d18d06c0

test:
  secret_key_base: efdad293e1517958015d91bb754c239e4f141ae906f262e01db4d5c78702c26f49b94d4ca6bed6bf3546ade48a7d931a37469f0f56a84c885589b796338b0321

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
